#! /bin/bash

sudo docker login --username=ybingc --password=Shandong01

sudo docker images
sudo docker push ybingc/ubuntu-helloworld
sudo docker rmi -f  ybingc/ubuntu-helloworld:firsttry
sudo docker pull ybingc/ubuntu-helloworld:firsttry
sudo docker images
