#! /bin/bash

docker login --username=ybingc --password=Shandong01

docker images
docker push ybingc/ubuntu-helloworld
docker rmi -f  ybingc/ubuntu-helloworld:firsttry
docker pull ybingc/ubuntu-helloworld:firsttry
docker images
